### PR TITLE
Example syscall.

### PR DESCRIPTION
**Pull request by dvc94ch**
Maybe something like this would work

### CODE REVIEW

**Comment by dvc94ch** [comment]
project dead already? :)

**Comment by elichai** [comment]
Not dead.
Just got too busy with other things.

I'll review your stuff this week and I really hope in a week or two I can get back to working on it

**Review by elichai — APPROVED** [review]
LGTM

**Comment by elichai** [comment]
FYI, I will probably remove the non linux call to `libc`.
I do not plan to link to anything in this project. this should be bare metal only.

**Comment by dvc94ch** [comment]
You can make libc a target specific dependency. Would be a shame to not support all unixes and not have a fallback.

**Comment by elichai** [comment]
I personally prefer to first finish linux and see if I can make a rust target without libc

**Pull request merged**
